version: "2"
services:

  mongors1n1:
    container_name: mongors1n1
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth --shardsvr --port 27017
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors1n1:/data/db

  mongors2n1:
    container_name: mongors2n1
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth --shardsvr --port 27017
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors2n1:/data/db

  mongocfg1:
    container_name: mongocfg1
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --dbpath /data/db --replSet mongorscfg --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    expose:
         - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongocfg1:/data/db

  mongos1:
    container_name: mongos1
    image: mongo:3.4
    depends_on:
      - mongocfg1
    command: mongos --configdb mongorscfg/mongocfg1:27017 --port 27017
    ports:
        - 127.0.0.1:27017:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro


